[package]
name = "test-project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aleph_client = { path = "../../aleph-node/aleph-client" }
ink_primitives = "4.0.0-beta.1"
ink-wrapper-types = { path = "../ink-wrapper-types" }
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2.3", default-features = false, features = ["derive"], optional = true }
async-trait = "0.1.64"
anyhow = "1.0.69"
tokio = "1.25.0"
sp-core = "16.0.0"
pallet-contracts-primitives = { git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "aleph-v0.9.33" }
